<?php


namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller
{
//    Контроллер который будет содержать общую логику приложения

    /*ХЗ почему но у меня название страницы и так Yii2-practice даже без данного метода
    Пришем данный метод, как временное решение вопроса названия страницы
    Данный метод выполняется перед каждым Экшеном*/

    /*public function beforeAction($action)
    {
//        Данный метод устанавливает значение title равное name которое мы берем из контейнера Yii::$app
    т.е. по факту мы вытащили значение свойства 'name' => 'Yii2-practice' из конфиг файла config/web
        $this->view->title = \Yii::$app->name;  // title = Yii2-practice
//        Обазательно возвращаем результаты родительского экшена
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/


}