<?php


namespace app\controllers;


use yii\web\Controller;

class AppController extends Controller
{
    /**
     * Общий(главный) контроллер приложения. Все остальные контроллеры должны наследовать его.
     * Данный контроллер Будет содержать общую логику приложения.
     */

//    Напишем защищенный метод для тайтла различных страниц:
    protected function setMeta($title = null, $keywords = null, $description = null)
    {
        /*Обращаемся к компоненту view, к его свойству title и в него будем записывать то, что будет
        передаваться при вызове данного метода(setMeta) в качестве $title*/
        $this->view->title = $title;
        /*Далее регистрируем метатеги для $keywords и $description:*/
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);

        /*Метод готов и далее используем его в наших экшенах в CategoryController*/
    }


    /*ХЗ почему но у меня название страницы и так Yii2-practice даже без данного метода
    Пришем данный метод, как временное решение вопроса названия страницы

    Существует набор методов которые выполняются до или после какого-нибудь события, например
    beforeAction, afterAction, beforeSave, afterSave

      Данный метод выполняется перед каждым Экшеном
    public function beforeAction($action)
    {
//        Данный метод устанавливает значение title равное name которое мы берем из контейнера Yii::$app
//        т.е. по факту мы вытащили значение свойства 'name' => 'Yii2-practice' из конфиг файла config/web
        $this->view->title = \Yii::$app->name;  // title = Yii2-practice
//        Обазательно возвращаем результаты родительского экшена
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }*/

}